spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:absolute_cinema}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:absolute_cinema123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}
