spring.application.name=cinema
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://hayabusa.proxy.rlwy.net:53977/mydb?serverTimezone=UTC&createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bOvqGVKoYXFbeIQAQvqCCfsHAVoWLnKi}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}